# Generated by Django 3.2.3 on 2021-06-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('jobapplicationDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobform.jobapplication')),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
