# Generated by Django 3.2.3 on 2021-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
