# Generated by Django 3.2.3 on 2021-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0002_alter_jobapplication_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='dob',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
