# Generated by Django 3.2.3 on 2021-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0003_alter_jobapplication_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='dob',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='fname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='lname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='relation_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='zip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
