# Generated by Django 3.2.3 on 2021-05-28 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0004_auto_20210528_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
