# Generated by Django 3.2.3 on 2021-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0005_jobapplication_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='BeginnerLaravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='BeginnerMYSQL',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='BeginnerOracle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ExpertLaravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ExpertMYSQL',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ExpertOracle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ExpertPHP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language1_read',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language1_speak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language1_write',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language2_read',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language2_speak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language2_write',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language3_Read',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language3_Speak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Language3_Write',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Laravel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='MideatorMYSQL',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='MideatorOracle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='MideatorPHP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Oracle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='PHP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='bachelor_course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='bachelor_score',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='bachelor_uni_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='bachelor_year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='beginnerPHP',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='currentCTC',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expectedCTC',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hsc_dip_board_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hsc_dip_score',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hsc_dip_year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='master_course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='master_score',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='master_uni_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='master_year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='noticeperiod',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_contact1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_contact2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_name1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_name2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_relation1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ref_relation2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ssc_board_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ssc_score',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ssc_year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company1_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company1_start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company2_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company2_end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company2_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company2_start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company3_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company3_end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company3_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company3_start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
