# Generated by Django 3.2.3 on 2021-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0006_auto_20210528_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='workexp_company1_end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
