# Generated by Django 3.2.3 on 2021-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0008_jobapplication_mysql'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='MideatorLaravel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
