# Generated by Django 3.2.3 on 2021-05-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobform', '0009_jobapplication_mideatorlaravel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplication',
            table='Applications',
        ),
    ]
